import math;
print(math.pi);
print(dir(math));
from math import pi;
print(pi);
from math import *;
print(sin(pi/2));
print("math module");
print("sine function of pi/2: ",sin(pi/2));
print("cosine function of 0: ",cos(0));
print("tangent function of pi/4: ",tan(pi/4));
print("arc sine function of 0: ",asin(0));
print("arc cosine function of 1: ",acos(1));
print("arc tangent function of 0: ",atan(0));
print("square root function of 625: ",sqrt(625));
print("2 raised power 8: ",pow(2,8));
print("logarithm of 100 (base 10): ",log10(100));
print("exdponential of 1 (base e): ",exp(1));
print("logarithm of 100 (base e): ",log(100));
print("absolute value of -9,2: : ",fabs(-9.2));
print("rounds to smallest integer not less than 6.7: ",ceil(6.7));
print("rounds to largest  integer not less than 6.7: ",floor(6.7));